webtalk_init -webtalk_dir /home/paul/work/fpga/Xilinx/artix7/projects/ds_sound/ds_sound.sim/sim_1/behav/xsim/xsim.dir/sim_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 27 21:07:43 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35f85e04-f53b-4185-b828-144ea6923e02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "31d26fbe709746299a3dd40061f8f34a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.2 Tina" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1467.423 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "20.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10010 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125848_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3930289999 -regid "" -xml /home/paul/work/fpga/Xilinx/artix7/projects/ds_sound/ds_sound.sim/sim_1/behav/xsim/xsim.dir/sim_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/paul/work/fpga/Xilinx/artix7/projects/ds_sound/ds_sound.sim/sim_1/behav/xsim/xsim.dir/sim_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/paul/work/fpga/Xilinx/artix7/projects/ds_sound/ds_sound.sim/sim_1/behav/xsim/xsim.dir/sim_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
