webtalk_init -webtalk_dir /home/paul/work/fpga/Xilinx/artix7/qmtech_minimig_tests/aars_video_out/aars_video_out.sim/sim_1/behav/xsim/xsim.dir/simulation_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan  8 20:50:54 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35f85e04-f53b-4185-b828-144ea6923e02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c1605e5a917348db912d114694394ebc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "48" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.3 Tricia" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2729.517 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "20.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "10" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "443 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "29 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "250" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "12" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.88_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "283944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3718606462 -regid "" -xml /home/paul/work/fpga/Xilinx/artix7/qmtech_minimig_tests/aars_video_out/aars_video_out.sim/sim_1/behav/xsim/xsim.dir/simulation_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/paul/work/fpga/Xilinx/artix7/qmtech_minimig_tests/aars_video_out/aars_video_out.sim/sim_1/behav/xsim/xsim.dir/simulation_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/paul/work/fpga/Xilinx/artix7/qmtech_minimig_tests/aars_video_out/aars_video_out.sim/sim_1/behav/xsim/xsim.dir/simulation_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
