# Clock oscillator
set_property PACKAGE_PIN N11 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
# Reset button
set_property PACKAGE_PIN K5 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
# Core board LED
set_property PACKAGE_PIN E6 [get_ports sys_led_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_led_n]

# LEDs to blink on the board
set_property PACKAGE_PIN P5 [get_ports {o_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_leds[0]]
set_property PACKAGE_PIN T3 [get_ports {o_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_leds[1]]
set_property PACKAGE_PIN T2 [get_ports {o_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_leds[2]]
set_property PACKAGE_PIN R1 [get_ports {o_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_leds[3]]
set_property PACKAGE_PIN N4 [get_ports {o_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_leds[4]]
set_property PACKAGE_PIN P3 [get_ports {o_leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_leds[5]]

# Floppy pins
set_property PACKAGE_PIN E1 [get_ports exp_02]
set_property IOSTANDARD LVCMOS33 [get_ports exp_02]
set_property PACKAGE_PIN F3 [get_ports exp_04]
set_property IOSTANDARD LVCMOS33 [get_ports exp_04]
set_property PACKAGE_PIN G2 [get_ports exp_08]
set_property IOSTANDARD LVCMOS33 [get_ports exp_08]
set_property PACKAGE_PIN G1 [get_ports exp_10]
set_property IOSTANDARD LVCMOS33 [get_ports exp_10]
set_property PACKAGE_PIN H2 [get_ports exp_12]
set_property IOSTANDARD LVCMOS33 [get_ports exp_12]
set_property PACKAGE_PIN H1 [get_ports exp_16]
set_property IOSTANDARD LVCMOS33 [get_ports exp_16]
set_property PACKAGE_PIN K1 [get_ports exp_18]
set_property IOSTANDARD LVCMOS33 [get_ports exp_18]
set_property PACKAGE_PIN J1 [get_ports exp_20]
set_property IOSTANDARD LVCMOS33 [get_ports exp_20]
set_property PACKAGE_PIN L3 [get_ports exp_22]
set_property IOSTANDARD LVCMOS33 [get_ports exp_22]
set_property PACKAGE_PIN L2 [get_ports exp_24]
set_property IOSTANDARD LVCMOS33 [get_ports exp_24]
set_property PACKAGE_PIN H5 [get_ports exp_26]
set_property IOSTANDARD LVCMOS33 [get_ports exp_26]
set_property PACKAGE_PIN H4 [get_ports exp_28]
set_property IOSTANDARD LVCMOS33 [get_ports exp_28]
set_property PACKAGE_PIN J3 [get_ports exp_30]
set_property IOSTANDARD LVCMOS33 [get_ports exp_30]
set_property PACKAGE_PIN H3 [get_ports exp_32]
set_property IOSTANDARD LVCMOS33 [get_ports exp_32]
set_property PACKAGE_PIN K3 [get_ports exp_34]
set_property IOSTANDARD LVCMOS33 [get_ports exp_34]
set_property PACKAGE_PIN K2 [get_ports exp_35]
set_property IOSTANDARD LVCMOS33 [get_ports exp_35]